name: CI/CD Pipeline â€“ Deploy Python App to AWS EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 010438510645
  ECR_REPOSITORY: python-app
  IMAGE_NAME: python-app
  EKS_CLUSTER_NAME: demo-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::010438510645:role/github-actions-eks-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

    - name: Tag and Push Image to ECR
      run: |
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

        docker push \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig \
          --region ${AWS_REGION} \
          --name ${EKS_CLUSTER_NAME}

    - name: Verify Cluster Access
      run: |
        kubectl get nodes
        kubectl get deployments || true

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/python-app \
          python-app=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

        kubectl rollout status deployment/python-app

