name: CI/CD Pipeline â€“ Deploy Python App to AWS EKS

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: python-app
  EKS_CLUSTER_NAME: demo-eks
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # 2. Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    # 3. Linting
    - name: Lint Code
      run: |
        pip install flake8
        flake8 app/ || echo "Lint warnings found"

    # 4. Testing
    - name: Run Tests
      run: |
        echo "Running tests"
        # pytest tests/

    # 5. AWS Auth (OIDC)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::010438510645:role/github-actions-eks-role
        aws-region: ${{ env.AWS_REGION }}

    # 6. ECR Login
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 7. Build Image
    - name: Build Docker Image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

    # 8. Security Scan
    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: $ECR_REPOSITORY:${{ env.IMAGE_TAG }}
        severity: HIGH,CRITICAL
        exit-code: 0

    # 9. Push Image
    - name: Push Image to Amazon ECR
      run: |
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          010438510645.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

        docker push \
          010438510645.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    # 10. Configure kubectl
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    # 11. Deploy
    - name: Deploy to EKS
      run: |
        kubectl set image deployment/python-app \
          python-app=010438510645.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAGp

