name: CI/CD Pipeline â€“ Deploy Python App to AWS EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 010438510645
  ECR_REPOSITORY: python-app
  IMAGE_NAME: python-app
  EKS_CLUSTER_NAME: demo-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Set Image Tag
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # 3. Configure AWS Credentials (OIDC or Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::010438510645:role/github-actions-eks-role
          aws-region: ${{ env.AWS_REGION }}

      # 4. Login to Amazon ECR (VERY IMPORTANT)
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 5. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      # 6. Tag & Push Image to ECR
      - name: Push Image to Amazon ECR
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      # 7. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      # 8. Configure kubectl for EKS
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      # 9. Verify Cluster Access
      - name: Verify EKS Access
        run: |
          kubectl get nodes
          kubectl get deployments || true

      # 10. Apply Kubernetes Manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # 11. Update Image & Rollout
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/python-app \
            python-app=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          kubectl rollout status deployment/python-app

